name: Go

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go      
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
        
    - name: Set up fdb
      run: 
        wget --no-check-certificate https://github.com/apple/foundationdb/releases/download/6.3.24/foundationdb-clients_6.3.24-1_amd64.deb;
        wget --no-check-certificate https://github.com/apple/foundationdb/releases/download/6.3.24/foundationdb-server_6.3.24-1_amd64.deb;
        sudo apt-get -y install ./foundationdb-clients_6.3.24-1_amd64.deb;        
        sudo apt-get -y install ./foundationdb-server_6.3.24-1_amd64.deb;
        sudo systemctl start foundationdb;
        sudo systemctl status foundationdb

    - name: Build
      env: 
        GO111MODULE: on
        GOPRIVATE: github.com/emqx
        CGO_ENABLED: 1
      run:  
        go mod tidy;
        go build -v ./...;
        ./testworkflow
   
  test:
    runs-on: ubuntu-latest
    needs: build
    secrets:
      USER: username
      PASSWORD: password
    steps:
    - name: unit test
      run: go test ./...

    - name: Deploy Stage
      id: myRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'http://localhost:5041/'
        method: 'GET'
        username: 'admin'
        password: 'public'
    - name: Show Response
      run: echo ${{ steps.myRequest.outputs.response }}