name: Go

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: set up fdb
      run: 
        wget --no-check-certificate https://github.com/apple/foundationdb/releases/download/6.3.24/foundationdb-clients_6.3.24-1_amd64.deb
        wget --no-check-certificate https://github.com/apple/foundationdb/releases/download/6.3.24/foundationdb-server_6.3.24-1_amd64.deb
        sudo apt install ./foundationdb-clients_6.3.24-1_amd64.deb
        sudo apt install ./foundationdb-server_6.3.24-1_amd64.deb
        systemctl start foundationdb
    - name: Build
      env: 
        GO111MODULE: on
        GOPRIVATE: github.com/emqx
        CGO_ENABLED: 1
      run:  
        go build -v ./...
