name: Go

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: 
        wget --no-check-certificate --content-disposition https://github.com/apple/foundationdb/releases/download/6.3.23/foundationdb-clients-6.3.23-1.el7.x86_64.rpm
        wget --no-check-certificate --content-disposition https://github.com/apple/foundationdb/releases/download/6.3.23/foundationdb-server-6.3.24-1.el7.x86_64.rpm
        sudo yum localinstall foundationdb-clients-6.3.24-1.el7.x86_64.rpm
        sudo yum localinstall foundationdb-server-6.3.24-1.el7.x86_64.rpm
        sudo systemctl start foundationdb
        go build -v ./...
